### PR TITLE
Update README.md

### LINKED ISSUE #74: Rename "Receipes" to "Workflows"
I think what's called "Receipes" here in this repository fits very well to what Miura et al define as "Workflows" in [https://link.springer.com/chapter/10.1007/978-3-030-22386-1_1](https://link.springer.com/chapter/10.1007/978-3-030-22386-1_1)

To prevent introducing a new term and the need to explain it, and differentiate it from the established term, I suggest to rename "receipes" to "workflows".

### PR DESCRIPTION
**Pull request by jo-mueller**
Fixes #74 

@haesleinhuepf - should I rename the respective folder in the `/docs`, too? Then I'll have to change a few more things in the documentation :)

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Sounds good @jo-mueller ! Better renaming things now than later when the documentation is growing 😉

**Comment by jo-mueller** [comment]
It seems that the error may be related to the tools menu:

```
___ ERROR collecting src/napari_stress/_tests/test_spherical_harmonic_fit.py ___
src/napari_stress/_tests/test_spherical_harmonic_fit.py:4: in <module>
    import napari_stress
src/napari_stress/__init__.py:3: in <module>
    from ._refine_surfaces import trace_refinement_of_surface
src/napari_stress/_refine_surfaces.py:[18](https://github.com/BiAPoL/napari-stress/runs/7089436107?check_suite_focus=true#step:8:19): in <module>
    from napari_tools_menu import register_function
/usr/share/miniconda/envs/test/lib/python3.7/site-packages/napari_tools_menu/__init__.py:9: in <module>
    import napari._qt
```

**Comment by jo-mueller** [comment]
May be related to [this issue?](https://github.com/haesleinhuepf/napari-tools-menu/issues/1)

**Comment by jo-mueller** [comment]
I created a separate issue (#93 ) for this problem. Since I only changed documentation in this PR, I'd go ahead and merge despite failing tests.

**Pull request merged**
